- name: '[CentOS] Installing Packages'
  yum:
    name: '{{ packages }}'
    state: latest
  vars:
    packages:
            - httpd
            - git
            - vim

- name: '[CentOS] Starting Httpd Service'
  service:
    name: httpd
    state: started
    enabled: yes

- name: 'Opening Web Port'
  iptables:
    chain: INPUT
    protocol: 80
    ctstate: NEW
    jump: ACCEPT
    comment: Accept Port 80 Network

- name: 'Cloning Master Repo'
  git:
    repo: '{{ repo }}'
    dest: /var/www/html
