- name: "Transferring Startup Script"
  synchronize:
    src: ./start.sh
    dest: /root/{{ folder_name }}/{{ game_name }}/
  #shell: cd /root/{{ folder_name }}/{{ game_name }} ; sh start.sh
  when: (state == "start")

- name: "Starting Game File"
  shell: cd /root/{{ folder_name }}/{{ game_name }} ; sh start.sh &
  when: (state == "start")

- name: "Stopping Game"
  shell: screen -X -S $(screen -ls | grep -i 'hldstest' | awk '{print $1}') quit
  when: (state == "stop")
